use chrono::Utc;
use ign::models::AppliedGitignore;
use ign::parser::GitignoreParser;
use std::collections::HashMap;
use std::fs;

#[test]
fn test_parse_empty_content() {
    let parsed = GitignoreParser::parse_content("");
    assert!(parsed.templates.is_empty());
    assert!(parsed.custom_content.is_none());
    assert!(parsed.template_blocks.is_empty());
}

#[test]
fn test_parse_unmanaged_plain_gitignore() {
    let plain = r#"# User custom file
node_modules/
.env
dist/
*.log
"#;
    let parsed = GitignoreParser::parse_content(plain);
    assert!(parsed.templates.is_empty());
    assert_eq!(
        parsed.custom_content,
        Some("# User custom file\nnode_modules/\n.env\ndist/\n*.log".to_string())
    );
}

#[test]
fn test_render_and_parse_lifecycle() {
    let mut applied = AppliedGitignore::default();

    let initial_templates = vec![
        (
            "Rust".to_string(),
            "/target\nCargo.lock\n**/*.rs.bk".to_string(),
        ),
        (
            "Global/macOS".to_string(),
            ".DS_Store\n.AppleDouble".to_string(),
        ),
    ];
    let added = GitignoreParser::add_templates(&mut applied, initial_templates);
    assert_eq!(added, vec!["Rust", "Global/macOS"]);

    applied.custom_content =
        Some("# Local developer overrides\nsecrets.json\n*.local".to_string());

    let rendered = GitignoreParser::render(&applied);

    // Verify rendered output has proper header and delimiters
    assert!(rendered.contains("# Generated by ign (GitHub gitignore CLI)"));
    assert!(rendered.contains("# Templates: Rust, Global/macOS"));
    assert!(rendered.contains("# Updated: "));
    assert!(rendered.contains("# --- BEGIN TEMPLATE: Rust ---"));
    assert!(rendered.contains("/target"));
    assert!(rendered.contains("# --- END TEMPLATE: Rust ---"));
    assert!(rendered.contains("# --- BEGIN TEMPLATE: Global/macOS ---"));
    assert!(rendered.contains(".DS_Store"));
    assert!(rendered.contains("# --- END TEMPLATE: Global/macOS ---"));
    assert!(rendered.contains("# --- BEGIN CUSTOM RULES ---"));
    assert!(rendered.contains("secrets.json"));
    assert!(rendered.contains("# --- END CUSTOM RULES ---"));

    // Parse back
    let parsed = GitignoreParser::parse_content(&rendered);
    assert_eq!(parsed.templates, vec!["Rust", "Global/macOS"]);
    assert_eq!(
        parsed.template_blocks.get("Rust").unwrap(),
        "/target\nCargo.lock\n**/*.rs.bk"
    );
    assert_eq!(
        parsed.template_blocks.get("Global/macOS").unwrap(),
        ".DS_Store\n.AppleDouble"
    );
    assert_eq!(
        parsed.custom_content,
        Some("# Local developer overrides\nsecrets.json\n*.local".to_string())
    );
}

#[test]
fn test_add_and_update_template_deduplication() {
    let mut applied = AppliedGitignore::default();

    GitignoreParser::add_templates(
        &mut applied,
        vec![("Rust".to_string(), "target/".to_string())],
    );
    assert_eq!(applied.templates, vec!["Rust"]);
    assert_eq!(applied.template_blocks.get("Rust").unwrap(), "target/");

    // Add again with updated content and case variation
    GitignoreParser::add_templates(
        &mut applied,
        vec![
            ("rust".to_string(), "/target\nCargo.lock".to_string()),
            ("Python".to_string(), "__pycache__/".to_string()),
        ],
    );

    // Rust should not be duplicated in templates list, but content updated
    assert_eq!(applied.templates, vec!["Rust", "Python"]);
    assert_eq!(
        applied.template_blocks.get("Rust").unwrap(),
        "/target\nCargo.lock"
    );
    assert_eq!(
        applied.template_blocks.get("Python").unwrap(),
        "__pycache__/"
    );
}

#[test]
fn test_remove_templates_by_short_or_full_name() {
    let mut applied = AppliedGitignore::default();
    GitignoreParser::add_templates(
        &mut applied,
        vec![
            ("Rust".to_string(), "target/".to_string()),
            ("Global/macOS".to_string(), ".DS_Store".to_string()),
            ("Global/JetBrains".to_string(), ".idea/".to_string()),
        ],
    );

    // Remove by short name "macos"
    let removed = GitignoreParser::remove_templates(&mut applied, &["macos".to_string()]);
    assert_eq!(removed, vec!["Global/macOS"]);
    assert_eq!(applied.templates, vec!["Rust", "Global/JetBrains"]);
    assert!(!applied.template_blocks.contains_key("Global/macOS"));

    // Remove by full name "Global/JetBrains"
    let removed2 =
        GitignoreParser::remove_templates(&mut applied, &["Global/JetBrains".to_string()]);
    assert_eq!(removed2, vec!["Global/JetBrains"]);
    assert_eq!(applied.templates, vec!["Rust"]);

    // Remove non-existent
    let removed3 = GitignoreParser::remove_templates(&mut applied, &["non_existent".to_string()]);
    assert!(removed3.is_empty());
}

#[test]
fn test_status_inspection() {
    let dir = tempfile::tempdir().unwrap();
    let file_path = dir.path().join(".gitignore");

    let applied = AppliedGitignore {
        templates: vec!["Rust".to_string()],
        created_at: Some(Utc::now()),
        updated_at: Some(Utc::now()),
        custom_content: Some("*.tmp\nbuild/".to_string()),
        template_blocks: HashMap::from([("Rust".to_string(), "/target".to_string())]),
    };

    let rendered = GitignoreParser::render(&applied);
    fs::write(&file_path, &rendered).unwrap();

    let status = GitignoreParser::get_status(&file_path, &applied);
    assert!(status.file_exists);
    assert!(status.managed_by_ign);
    assert_eq!(status.templates_count, 1);
    assert_eq!(status.templates, vec!["Rust"]);
    assert!(status.has_custom_rules);
    assert_eq!(status.custom_rules_lines, 2);
    assert_eq!(status.custom_rules, Some("*.tmp\nbuild/".to_string()));
    assert!(status.total_lines > 5);
}

#[test]
fn test_parse_dates_header() {
    let sample = r#"# ==============================================================================
# Generated by ign (GitHub gitignore CLI)
# Templates: Rust
# Created: 2026-08-29 12:00:00 UTC
# Updated: 2026-08-29 12:30:00 UTC
# ==============================================================================

# --- BEGIN TEMPLATE: Rust ---
/target
# --- END TEMPLATE: Rust ---
"#;
    let parsed = GitignoreParser::parse_content(sample);
    assert!(parsed.created_at.is_some());
    assert!(parsed.updated_at.is_some());
    assert_eq!(parsed.templates, vec!["Rust"]);
}

#[test]
fn test_preserve_loose_custom_rules() {
    let sample = r#"# ==============================================================================
# Generated by ign (GitHub gitignore CLI)
# Templates: Rust
# Updated: 2026-08-29 12:00:00 UTC
# ==============================================================================

# --- BEGIN TEMPLATE: Rust ---
/target
# --- END TEMPLATE: Rust ---

# User manually added lines below
local.env
scratch/
"#;
    let parsed = GitignoreParser::parse_content(sample);
    assert_eq!(parsed.templates, vec!["Rust"]);
    assert!(parsed.custom_content.is_some());
    let custom = parsed.custom_content.unwrap();
    assert!(custom.contains("local.env"));
    assert!(custom.contains("scratch/"));
}
