use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use regex::Regex;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

use crate::models::{AppliedGitignore, GitignoreStatus};

const HEADER_BORDER: &str = "# ==============================================================================";
const HEADER_GENERATED: &str = "# Generated by ign (GitHub gitignore CLI)";
const TEMPLATE_BEGIN_PREFIX: &str = "# --- BEGIN TEMPLATE: ";
const TEMPLATE_END_PREFIX: &str = "# --- END TEMPLATE: ";
const CUSTOM_BEGIN: &str = "# --- BEGIN CUSTOM RULES ---";
const CUSTOM_END: &str = "# --- END CUSTOM RULES ---";

/// Parser and manager for `.gitignore` file contents
pub struct GitignoreParser;

impl GitignoreParser {
    /// Read and parse a `.gitignore` file from the specified path
    pub fn read_from_file<P: AsRef<Path>>(path: P) -> Result<AppliedGitignore> {
        let path_ref = path.as_ref();
        if !path_ref.exists() {
            return Ok(AppliedGitignore::default());
        }

        let content = fs::read_to_string(path_ref)
            .with_context(|| format!("Failed to read file from {:?}", path_ref))?;

        Ok(Self::parse_content(&content))
    }

    /// Parse a `.gitignore` content string into an `AppliedGitignore` struct
    pub fn parse_content(content: &str) -> AppliedGitignore {
        if content.trim().is_empty() {
            return AppliedGitignore::default();
        }

        // Check if this file contains ign markers
        let has_ign_markers = content.contains(TEMPLATE_BEGIN_PREFIX)
            || content.contains(HEADER_GENERATED)
            || content.contains(CUSTOM_BEGIN);

        if !has_ign_markers {
            // Unmanaged existing .gitignore -> treat entire content as custom rules
            return AppliedGitignore {
                templates: Vec::new(),
                created_at: None,
                updated_at: None,
                custom_content: Some(content.trim().to_string()),
                template_blocks: HashMap::new(),
            };
        }

        let lines: Vec<&str> = content.lines().collect();

        // Extract metadata headers
        let created_at = Self::extract_header_date(&lines, "Created");
        let updated_at = Self::extract_header_date(&lines, "Updated");

        let mut templates = Vec::new();
        let mut template_blocks = HashMap::new();
        let mut custom_lines = Vec::new();

        let mut current_template: Option<String> = None;
        let mut current_template_lines: Vec<&str> = Vec::new();
        let mut in_custom_block = false;
        let mut in_header = false;

        let begin_re = Regex::new(r"^# --- BEGIN TEMPLATE:\s*(.+?)\s*---$").unwrap();
        let end_re = Regex::new(r"^# --- END TEMPLATE:\s*(.+?)\s*---$").unwrap();

        for line in &lines {
            let trimmed = line.trim();

            if trimmed == HEADER_BORDER {
                in_header = !in_header;
                continue;
            }

            if in_header {
                // Header line, ignore in custom content
                continue;
            }

            if let Some(caps) = begin_re.captures(trimmed) {
                let name = caps.get(1).map_or("", |m| m.as_str()).to_string();
                current_template = Some(name);
                current_template_lines.clear();
                continue;
            }

            if let Some(caps) = end_re.captures(trimmed) {
                let name = caps.get(1).map_or("", |m| m.as_str()).to_string();
                if let Some(ref curr) = current_template {
                    let block_name = if curr == &name { curr.clone() } else { name };
                    let block_str = current_template_lines.join("\n").trim().to_string();
                    if !templates.contains(&block_name) {
                        templates.push(block_name.clone());
                    }
                    template_blocks.insert(block_name, block_str);
                    current_template = None;
                    current_template_lines.clear();
                }
                continue;
            }

            if trimmed == CUSTOM_BEGIN {
                in_custom_block = true;
                continue;
            }

            if trimmed == CUSTOM_END {
                in_custom_block = false;
                continue;
            }

            if let Some(_) = current_template {
                current_template_lines.push(line);
            } else if in_custom_block {
                custom_lines.push(*line);
            } else {
                // Lines outside of template blocks and custom blocks
                // If not empty, preserve as custom rules to never lose user edits
                if !trimmed.is_empty() && !trimmed.starts_with("# Generated by ign") {
                    custom_lines.push(*line);
                }
            }
        }

        let custom_content = if custom_lines.is_empty() {
            None
        } else {
            let s = custom_lines.join("\n").trim().to_string();
            if s.is_empty() {
                None
            } else {
                Some(s)
            }
        };

        AppliedGitignore {
            templates,
            created_at,
            updated_at,
            custom_content,
            template_blocks,
        }
    }

    /// Render an `AppliedGitignore` into a standard formatted `.gitignore` string
    pub fn render(applied: &AppliedGitignore) -> String {
        let mut out = String::new();

        let now = Utc::now();
        let updated_time = applied.updated_at.unwrap_or(now);
        let updated_str = updated_time.format("%Y-%m-%d %H:%M:%S UTC").to_string();

        // Header
        out.push_str(HEADER_BORDER);
        out.push('\n');
        out.push_str(HEADER_GENERATED);
        out.push('\n');
        if !applied.templates.is_empty() {
            out.push_str(&format!("# Templates: {}\n", applied.templates.join(", ")));
        } else {
            out.push_str("# Templates: (none)\n");
        }
        if let Some(created) = applied.created_at {
            out.push_str(&format!(
                "# Created: {}\n",
                created.format("%Y-%m-%d %H:%M:%S UTC")
            ));
        }
        out.push_str(&format!("# Updated: {}\n", updated_str));
        out.push_str(HEADER_BORDER);
        out.push_str("\n\n");

        // Template Blocks
        for template_name in &applied.templates {
            if let Some(block) = applied.template_blocks.get(template_name) {
                out.push_str(&format!("{}{template_name} ---\n", TEMPLATE_BEGIN_PREFIX));
                let trimmed_block = block.trim();
                if !trimmed_block.is_empty() {
                    out.push_str(trimmed_block);
                    out.push('\n');
                }
                out.push_str(&format!("{}{template_name} ---\n\n", TEMPLATE_END_PREFIX));
            }
        }

        // Custom Rules Block
        if let Some(ref custom) = applied.custom_content {
            let trimmed_custom = custom.trim();
            if !trimmed_custom.is_empty() {
                out.push_str(CUSTOM_BEGIN);
                out.push('\n');
                out.push_str(trimmed_custom);
                out.push('\n');
                out.push_str(CUSTOM_END);
                out.push('\n');
            }
        }

        out
    }

    /// Add or update templates in an `AppliedGitignore`
    pub fn add_templates(
        applied: &mut AppliedGitignore,
        new_templates: Vec<(String, String)>,
    ) -> Vec<String> {
        let mut added_names = Vec::new();
        let now = Utc::now();

        if applied.created_at.is_none() {
            applied.created_at = Some(now);
        }
        applied.updated_at = Some(now);

        for (name, content) in new_templates {
            let existing_key = applied
                .templates
                .iter()
                .find(|t| t.eq_ignore_ascii_case(&name))
                .cloned();

            if let Some(key) = existing_key {
                // Update existing block
                applied.template_blocks.insert(key.clone(), content);
                added_names.push(key);
            } else {
                // Add new template
                applied.templates.push(name.clone());
                applied.template_blocks.insert(name.clone(), content);
                added_names.push(name);
            }
        }

        added_names
    }

    /// Remove templates matching the given query names (case-insensitive)
    pub fn remove_templates(
        applied: &mut AppliedGitignore,
        to_remove: &[String],
    ) -> Vec<String> {
        let mut removed = Vec::new();

        for query in to_remove {
            let q_norm = query.trim().to_lowercase();
            let mut matched_indices = Vec::new();

            for (idx, name) in applied.templates.iter().enumerate() {
                let name_norm = name.to_lowercase();
                let base_name = name.split('/').last().unwrap_or(name).to_lowercase();

                if name_norm == q_norm || base_name == q_norm {
                    matched_indices.push(idx);
                }
            }

            // Remove in reverse order so indices remain valid
            for idx in matched_indices.into_iter().rev() {
                let name = applied.templates.remove(idx);
                applied.template_blocks.remove(&name);
                removed.push(name);
            }
        }

        if !removed.is_empty() {
            applied.updated_at = Some(Utc::now());
        }

        removed
    }

    /// Inspect status of `.gitignore` file and parsed representation
    pub fn get_status<P: AsRef<Path>>(path: P, applied: &AppliedGitignore) -> GitignoreStatus {
        let path_ref = path.as_ref();
        let path_str = path_ref.to_string_lossy().to_string();
        let file_exists = path_ref.exists();

        let (total_lines, managed) = if file_exists {
            let content = fs::read_to_string(path_ref).unwrap_or_default();
            let is_managed =
                content.contains(TEMPLATE_BEGIN_PREFIX) || content.contains(HEADER_GENERATED);
            (content.lines().count(), is_managed)
        } else {
            (0, false)
        };

        let custom_lines = applied
            .custom_content
            .as_ref()
            .map(|c| c.lines().count())
            .unwrap_or(0);

        GitignoreStatus {
            file_exists,
            path: path_str,
            managed_by_ign: managed,
            templates_count: applied.templates.len(),
            templates: applied.templates.clone(),
            created_at: applied.created_at,
            updated_at: applied.updated_at,
            has_custom_rules: applied.custom_content.is_some(),
            custom_rules_lines: custom_lines,
            custom_rules: applied.custom_content.clone(),
            total_lines,
        }
    }

    /// Helper to extract timestamp from header comment lines
    fn extract_header_date(lines: &[&str], key: &str) -> Option<DateTime<Utc>> {
        let prefix = format!("# {}: ", key);
        for line in lines {
            let trimmed = line.trim();
            if trimmed.starts_with(&prefix) {
                let val = trimmed.strip_prefix(&prefix)?.trim();
                return Self::parse_date_flexible(val);
            }
        }
        None
    }

    /// Helper to parse datetime flexibly from various header formats
    fn parse_date_flexible(val: &str) -> Option<DateTime<Utc>> {
        if let Ok(dt) = DateTime::parse_from_rfc3339(val) {
            return Some(dt.with_timezone(&Utc));
        }
        if let Ok(naive) = chrono::NaiveDateTime::parse_from_str(val, "%Y-%m-%d %H:%M:%S UTC") {
            return Some(DateTime::<Utc>::from_naive_utc_and_offset(naive, Utc));
        }
        if let Ok(naive) = chrono::NaiveDateTime::parse_from_str(val, "%Y-%m-%d %H:%M:%S") {
            return Some(DateTime::<Utc>::from_naive_utc_and_offset(naive, Utc));
        }
        if let Ok(dt) = DateTime::parse_from_str(val, "%Y-%m-%d %H:%M:%S %z") {
            return Some(dt.with_timezone(&Utc));
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_unmanaged_gitignore() {
        let unmanaged = "target/\n*.log\n.env\n";
        let parsed = GitignoreParser::parse_content(unmanaged);
        assert!(parsed.templates.is_empty());
        assert_eq!(parsed.custom_content, Some("target/\n*.log\n.env".to_string()));
    }

    #[test]
    fn test_render_and_parse_roundtrip() {
        let mut applied = AppliedGitignore::default();
        let new_templates = vec![
            ("Rust".to_string(), "/target\n**/*.rs.bk\nCargo.lock".to_string()),
            ("Global/macOS".to_string(), ".DS_Store\n.AppleDouble".to_string()),
        ];
        GitignoreParser::add_templates(&mut applied, new_templates);
        applied.custom_content = Some("# My local rule\nsecret.key".to_string());

        let rendered = GitignoreParser::render(&applied);
        assert!(rendered.contains("# --- BEGIN TEMPLATE: Rust ---"));
        assert!(rendered.contains("# --- BEGIN TEMPLATE: Global/macOS ---"));
        assert!(rendered.contains("# --- BEGIN CUSTOM RULES ---"));
        assert!(rendered.contains("secret.key"));

        let parsed = GitignoreParser::parse_content(&rendered);
        assert_eq!(parsed.templates, vec!["Rust".to_string(), "Global/macOS".to_string()]);
        assert!(parsed.template_blocks.contains_key("Rust"));
        assert!(parsed.template_blocks.contains_key("Global/macOS"));
        assert_eq!(parsed.custom_content, Some("# My local rule\nsecret.key".to_string()));
    }

    #[test]
    fn test_remove_templates() {
        let mut applied = AppliedGitignore::default();
        let new_templates = vec![
            ("Rust".to_string(), "target/".to_string()),
            ("Global/macOS".to_string(), ".DS_Store".to_string()),
            ("Python".to_string(), "__pycache__/".to_string()),
        ];
        GitignoreParser::add_templates(&mut applied, new_templates);

        let removed = GitignoreParser::remove_templates(&mut applied, &["macos".to_string()]);
        assert_eq!(removed, vec!["Global/macOS".to_string()]);
        assert_eq!(applied.templates, vec!["Rust".to_string(), "Python".to_string()]);
        assert!(!applied.template_blocks.contains_key("Global/macOS"));
    }

    #[test]
    fn test_add_templates_preserves_custom_rules() {
        let mut applied = GitignoreParser::parse_content("custom_dir/\nmy_config.yaml\n");
        assert_eq!(applied.custom_content, Some("custom_dir/\nmy_config.yaml".to_string()));

        GitignoreParser::add_templates(&mut applied, vec![("Rust".to_string(), "target/".to_string())]);

        assert_eq!(applied.templates, vec!["Rust".to_string()]);
        assert_eq!(applied.custom_content, Some("custom_dir/\nmy_config.yaml".to_string()));

        let rendered = GitignoreParser::render(&applied);
        assert!(rendered.contains("custom_dir/\nmy_config.yaml"));
        assert!(rendered.contains("target/"));
    }
}
